{% set name = "markov-clustering" %}
{% set version = "0.0.6.dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/markov_clustering-{{ version }}.tar.gz
  sha256: 8f72eee0ee5d9bfbab1b28bbfa95eaa020b2bba64b528ce45030b8b4300ecf33

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - numpy
    - scipy >=0.19.0
    - scikit-learn

test:
  imports:
    - markov_clustering
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/guyallard/markov_clustering.git
  summary: Implementation of the Markov clustering (MCL) algorithm in python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
